version: '3.0'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=catalyst
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
